import dotenv from 'dotenv';
import mongoose from 'mongoose';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

import { connectDatabase } from '../config/database.js';
import User from '../models/User.js';

const MEN = ["KAZEMBE EDGAR","CHANSA CHILESHE","PHIRI DIXON","MWALE OWEN","CHILESHE ROBERT","SOKO SYDNEY","MWALE JORDAN","SIMBEYE PETER","HAMAYANGWE NAKALANGA","ABEDNIGO KUNDA","MABO KOMBE SNR","MWALE BLESSING","SIMBAYA RICHARD","SIMUKONDA JONATHAN","MALUNGA MWAMBA","BANDA KONDWANI","MWALE BENJAMIN","NKHATA MAXWELL","MABO KOMBE JNR","N'GANDU MOSES","JERMAINE HANKINS","NKHOMA VICTOR","MUTAYACHALO KANJA","CHABU JUSTINE","MUMBI JUSTINE","MVULA ALEX","BANDA GRANT","CHISHALA MACMILLAN","BANDA MUMANGO","MWEENE KALEBI","MBULO RONALD","MULENGA MALAMBO","NTUMBA SYLVESTER","SIMBAYA EDWIN","MUKUPA ANDREW","LUWIKA NATHAN","CHICHIMA ISAAC","MANSOUR HITHAM","SANDO HECTOR","BANDA SYLVESTER","HANGWEWE GIFT","JONATHAN MAVUKA","MULENGA REUBEN","HAMAYANGWE NABUSANGA","MWANZA FRED","PHIRI BERNARD","JOSEPHAT NSAKANYA","NDEFWAI LYTON","GONDWE UNGWELU","NAWA ALBERT","SYDNEY MATETA","MUTALE MULENGA","CHIBOLELA BENNY","KAONGA KENAN","SILOMBA IVWANANJI","MUSONDA MAPALO","JERE PATULANI","MILETIC PAVLE","NGALASA ANDREW","CHIMFWEMBE LESA","JUSTIN MUTALE","KONDWANI GONDWE CHIRWA","KENAN CHIBALE","DAKA MELVIN","MULENGA MUONGA EZRA","TEMBO CHAZANGA","ZULU CHILITO","CHILUBA CHANDA","KAPINI ELIJAH","CHANDA JUSTINE","MAMFUNDA CHARLES","CHRISTOPHER MWANSA","AHMED MANSOUR","OM GUPTA","NSAMA CHILESHE","EMMANUEL NSOFWA","COSTA DAVID","FRANCIS SIMFUKWE","JOEL MBAZIMA","ELISHA SILUNBWE","ROSSIGNOL THOMAS","KANGAZA GIFT","PHAKATI REVAI","BOWA DANIEL","KAMANGA POINT","LUYANDO KALEBI","BURROWS JACK","KABANDA MUSONDA","MULENGA MAYBIN","KANYANTA GERALD","MWANZA JOE","SAMPA REMMY","CHOLA JOSEPH","KALUNGA EDGAR","CHILESHE MISHECK","KAI MULENGA","EUGINE HAMIYANDA","MOSES MONTA","CHIMBA PHIRI","JOSHUA BWALE","GWIRA THEMBIKILE","SAILI GREG","PHIRI NELSON","MUSANA FUNGAI","MUSONDA MWAMBA","SARAN SHIVAN","ZULU ZAIN","ACTON MATHEW","VALAND ADARSH","PHIRI CHIYESO","CHANDA MWANZA","MULENGA FIDELITY","SEBASTIAN MORONELL","CHONYA DERRICK","CUMMINGS SCOT","CHITANDA IAN","MWENYA MUBANGA","MWANGELWA EMMANUEL","SEAMAN MATTHEW","KAN'GOMBE GEUTHAN"];
const WOMEN = ["CHRISTABEL CHISONGO","ISABEL CHISONGO","MARGARET CHEWE","SORAYA MUMENA","MITRESS NALWIZYA","MUKANGWA SIAME","BEATRICE PHIRI","NALUNGWE NATASHA","MUTALE MAGGIE","ANGELA MWANSA","FEBBY CHILEMBO","VIOLET MULENGA","DIANA KITAIN","BLESSINGS NGULUBE","JANET MWAPE","ALICE MULENGA SOKO","KANYAMA HOPE","KABANSHI MAGRET","MWELWA FAITH","MWILA IREEN","MUKUKA MWENYA","SAZAMBILE PATRICIA","RUTH NYIRENDA","GONDWE DIANA","CHEWE EMMY","BALAMURALI TEJESVI","LISA CHISONGO","WINFRIDAH LUBEMBA","KAYLA MUIMO","JESSY MUSUNGA","CHIPULU NATASHA","MEDIA CHISWASWA","DEBRA BANDA MATETA","LETISHA CHIKWA","MWANSA MAMBWE","NALWIZYA JOYCE","PATRICIA CHIBESA","NAOMI CHILESHE","MULIMA PENELOPE","NKOLE FELISTUS","FAITH KAMWANGA","ISABLE KAPOSA","ROYDAH MWASA","TIYAMIKE NAMONJE","FAITH NAMBAYA","KONDWANI NAMBU","ZYNAB MUSOMA","BUTEMWA SHAMANO","MUSONDA CHANDA","YOLANDA PANTOJA","MUNDIA IMBOELA","CHIBESA LUBEMBA","DENISE MBAZIMA","MPHANDE PURITY","KOMBE NYENDWA GORRET","MWALE ESNART"];

const ZPIN_OVERRIDES = {
  'ABEDNIGO KUNDA':    'ZTAS0021',
  'MABO KOMBE JNR':    'ZTAJ0084',
  'PHIRI DIXON':       'ZTAS0064',
  'CHISHALA MACMILLAN':'ZTAJ0203',
  'MUMBI JUSTINE':     'ZTAS0036',
  "N'GANDU MOSES":     'ZTAS0067',
  'ALICE MULENGA SOKO':'ZTAS0113',
};

const tryFind = async (fullName) => {
  const key = fullName.trim().toUpperCase();
  if (ZPIN_OVERRIDES[key]) {
    const u = await User.findOne({ zpin: ZPIN_OVERRIDES[key] });
    if (u) return u;
  }
  const parts = fullName.trim().split(/\s+/);
  if (parts.length < 2) return null;
  let u = await User.findOne({ lastName: new RegExp(`^${parts[0].replace(/'/g, "\\'")}$`,'i'), firstName: new RegExp(`^${parts.slice(1).join(' ').replace(/'/g, "\\'")}$`,'i') });
  if (u) return u;
  u = await User.findOne({ firstName: new RegExp(`^${parts[0].replace(/'/g, "\\'")}$`,'i'), lastName: new RegExp(`^${parts.slice(1).join(' ').replace(/'/g, "\\'")}$`,'i') });
  return u;
};

const run = async () => {
  await connectDatabase();

  for (const [label, list] of [['MEN SENIOR', MEN], ['WOMEN SENIOR', WOMEN]]) {
    console.log(`\n=== ${label} ===`);
    const unmatched = [];
    for (const name of list) {
      const u = await tryFind(name);
      if (!u) unmatched.push(name);
    }
    if (unmatched.length === 0) {
      console.log('  All matched to ZPIN accounts!');
    } else {
      console.log(`  ${unmatched.length} unmatched (no ZPIN account found):`);
      unmatched.forEach(n => console.log(`    - ${n}`));
    }
  }

  await mongoose.disconnect();
};

run().catch(err => { console.error(err); process.exit(1); });
