/**
 * One-time seed: junior + senior doubles rankings from ZTA 2026 Google Sheet.
 * Safe to re-run — skips records that already exist for the same name+category+period.
 * Does NOT touch men_senior or women_senior.
 */
import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Ranking from '../models/Ranking.js';
import User from '../models/User.js';

dotenv.config();

const PERIOD = '2026';
const SEED_DATE = new Date('2026-01-01');
const SEED_TOURNAMENT = 'Opening Balance 2026';

// [rank, name, points, club?]
const DATA = {
  boys_10u: [
    [1,'NZELU ULENDO',465],
    [2,'ANGLOBERT MATETA',289],
    [3,'SHAWN MUIMO',144],
    [4,'SHAYNE T. NTUMBA',117],
    [5,'ISAAC NGANDWE',54],
    [6,'ALEJANDRO KAWIMBE',53],
    [7,'BWALYA MABO',45],
    [8,'JEREMIAH SOKO',41],
    [9,'KALEBI LUMUNO',39],
    [10,'ALINANSWE CHELLA',27],
    [10,'NAIK KAHAAN',27],
    [10,'DANIEL CHUNGU',27],
    [13,'MUBILA JOHN',18],
    [14,'CHABOTA ZULU',10],
    [15,'TAPELO CHILESHE',9],
    [15,'WIHANN MANS',9],
    [15,'DANIEL MERWE',9],
    [15,'CHUNDU YAMIKO',9],
    [15,'SICHULA SUWILANJI',9],
    [15,'NIEKERK EON',9],
    [15,'NDABALA BUPE',9],
    [15,'GAGE LUCA',9],
    [15,'REEVAN NAIK',9],
    [15,'EMMANUEL BUNDA',9],
    [25,'EDWARD ZULU',5],
    [25,'NABUYANDA MUSEMO',5],
    [25,'DE VALDES SAMAI',5],
    [28,'TAPELO MWANGALA',0],
  ],
  boys_12u: [
    [1,'GIFT MULENGA',500],
    [2,'ISRAEL SOKO',252],
    [3,'FIDELIS STIMATA',156],
    [4,'DIVINE CHALWE',108],
    [5,'KING SINGOYI',100],
    [6,'MARK PHIRI',90],
    [7,'JULIAN ACTON',54],
    [8,'SHEKINAH CHOMBA',36],
    [8,'MARTIN F. VAZQUEZ',36],
    [8,'DICKSON KUMWENDA',36],
    [8,'CHOMBA EVANS',36],
    [12,'MATHIAS ROMERO',18],
    [12,'CHISENGA CHENGELO',18],
    [12,'DIEGO VILLANTOY',18],
    [12,'NORMAN NILS',18],
    [12,'SILUMBE KAFULA',18],
    [17,'LUCAS TORRES',9],
    [17,'CHRISTOPHER CHILUPULA',9],
    [17,'RAYMOND MUTAKA',9],
    [17,'SIMON MUBANDA',9],
    [17,'POTTIBOYINA TARAK',9],
    [22,'GOA HUN',0],
    [22,'ANDRE SIKANYIKA',0],
    [22,'CHUME KAMBOLE',0],
    [22,'CHRISTOPHER SIKOMBWE',0],
    [22,'EMMANUEL TEMBO',0],
    [22,'ABRAHAM MWANZA',0],
    [22,'ELIAS LUNGU',0],
    [22,'MIKE MPANDE',0],
    [22,'MICHAEL CHEWE',0],
    [22,'MICHAEL KALUNGA',0],
    [22,'ZION S. MULENGA',0],
    [22,'MARLEY NENOT',0],
  ],
  boys_14u: [
    [1,'MAPALO MULENGA',460],
    [2,'CHRISTIAN MABO',208],
    [3,'LUYANDO KALEBI',162],
    [4,'MUKUKA MAPEPO',83],
    [5,'VAZQUEZ MARTIN',54],
    [6,'MUTALE MULENGA',36],
    [7,'DAVIES KAUNDA',32],
    [7,'MOSES CHAMA',32],
    [9,'ELIJAH NYIRENDA',27],
    [9,'GASPER MAREK',27],
    [9,'TORRES LUCAS',27],
    [9,'NAIK KUSH',27],
    [13,'GODFREY MWANZA',19],
    [14,'SANGWANI WALUSUNGU',18],
    [15,'BENAIH SIWALE',14],
    [16,'RAYMOND CHAKO',9],
    [16,'EMMANUEL BANDA',9],
    [16,'IBRAHIM AADIL',9],
    [16,'PRINCE BANDA',9],
    [16,'CHILUFYA KAUNDA',9],
    [16,'LUNGU LUNGILE',9],
    [22,'EMMANUEL MWAMBA',5],
    [22,'GANIZANI SOKO',5],
    [22,'BRAIDY HANKINGS',5],
  ],
  boys_16u: [
    [1,'ELISHA SILUNBWE',304],
    [2,'PAVLE MILETIC',136],
    [3,'JONATHAN MAVUKA',123],
    [4,'SHADERICK CHILESHE',114],
    [5,'NATHAN NTHWALA',99],
    [6,'KROUPNIK ROMAN',36],
    [7,'GERSHOM CHIUNDE',18],
    [7,'FABBRI ALESSANDRO',18],
    [7,'ELIJAH KALUNGA',18],
    [7,'ELIJAH NYIRENDA',18],
    [11,'GIFT SAKAKONGE',14],
    [11,'JAMEL KOMBE',14],
    [13,'AHMED MANSOUR',9],
    [13,'KONDWANI MWANZA',9],
    [13,'EMMANUEL MULENGA',9],
    [13,'JOHN MALAMA',9],
    [13,'LATHAM PANDWE',9],
    [13,'KENNEDY ZULU',9],
    [13,'SMITH VILLANTOYI',9],
    [20,'JOSEPH KAWIMBE',0],
    [20,'ALEX MUBITA',0],
    [20,'OSCAR LUBINDA',0],
    [20,'CHRIS SIMUCHIMBA',0],
    [20,'WACHIZYA MUNSHYA',0],
    [20,'ELISTONE MANDA',0],
    [20,'THOM NENOT',0],
    [20,'BRIAN BUNDA',0],
    [20,'ANDREW NGOSA',0],
    [20,'EVANS MULENGA',0],
    [20,'ABEL SHAMANO',0],
    [20,'GIFT MWANGO',0],
    [20,'ANDREW TEMBO',0],
    [20,'WACHISA MUNSHYA',0],
    [20,'EMMANUEL MWANZA',0],
  ],
  boys_18u: [
    [1,'MACMILLAN CHISHALA',388],
    [2,'FRED MWANZA',338],
    [3,'REUBEN MULENGA',250],
    [4,'MALAMBO MULENGA',159],
    [5,'ALBERT NAWA',105],
    [6,'KOMBE MABO JR',100],
    [7,'JUSTIN CHANDA',96],
    [8,'KONDWANI BANDA',90],
    [9,'CHIMBA PHIRI',72],
    [10,'LAVU NGULUTA',54],
    [11,'PETER MLAUZI',45],
    [12,'MATHEW ACTON',36],
    [12,'JEFFERSON MULENGA',36],
    [12,'ELIJAH KAPINI',36],
    [12,'MILETIC PAVLE',36],
    [16,'MILIMO NZALA',27],
    [17,'CHANDA MWANZA',18],
    [17,'GANIZANI SOKO',18],
    [17,'EUGINE HAMIYANDA',18],
    [17,'MARK CHIRWA',18],
    [17,'EVANS MUSONDA',18],
    [17,'EMMANUEL CHEWE',18],
    [17,'IVWANANJI SIKANYIKA',18],
    [17,'BENJAMIN NYIRENDA',18],
    [17,'MULENGA EMMANUEL',18],
    [27,'DANIEL BOWA',9],
    [27,'EMMANUEL CHIRWA',9],
    [27,'EDGAR KALUNGA',9],
    [27,'YAMIKANI NJOVU',9],
    [27,'CHARLES MWALE',9],
    [27,'MANSOUR AHMED',9],
    [27,'ABLE NGUNI',9],
    [27,'BANDA PRINCE',9],
  ],
  girls_10u: [
    [1,'GETRUDE MULENGA',508],
    [2,'MERCY MWAPE',298],
    [3,'NAMA ALINJAVWA',147],
    [4,'GLORIA NAKANIKA',127],
    [5,'TIYAMIKA SHAMANO',63],
    [6,'BUTEMWE NAMA',54],
    [6,'JOSEPHINE KATONGO',54],
    [8,'CHARITY MWALE',36],
    [8,'GIVEN MUSONDA',36],
    [10,'ROBERTS JAZMINE',18],
    [10,'ROBERTS DANIELLE',18],
    [10,'WANA CHITAMBALA',18],
    [10,'CHAMA CHAMULULU',18],
    [10,'NOWOMUGISHA LISA',18],
    [10,'SILUMBE CHIBESA',18],
    [10,'KAHENYA BUPE',18],
    [10,'KASANGA ZEQUISHA',18],
    [18,'SERAH MWANSA',9],
    [18,'ANNEL KAWEL',9],
    [18,'DIANA BANDA',9],
    [18,'CELESTE PALOMARES',9],
    [18,'KAMPAMBA MULENGA',9],
    [18,'SOKO GLORY',9],
    [18,'URSIC LUCIJA',9],
  ],
  girls_12u: [
    [1,'SHANEY MATETA',560],
    [2,'SHALOM SOKO',352],
    [3,'MONICA MTONGA',268],
    [4,'NATAIZYA NAMWILA',159],
    [5,'CHARITY CHILESHE',136],
    [6,'GRACE CHILEYA',90],
    [7,'TAONGA CHISOPA',81],
    [7,'LUYANDO SIMALUMBA',81],
    [9,'ELIZABETH KAPINI',78],
    [10,'CHILUUBA MWAPE',72],
    [11,'MIRACLE LUMASA',63],
    [12,'MALUMBO MWANZA',54],
    [13,'VAN DER MERWE',36],
    [14,'GRACE MULENGA',18],
    [14,'GASPEROVA EMELLIE',18],
    [14,'KAUNDA CHABALA',18],
    [17,'CHUMA KAMBOLE',9],
    [17,'KETISHA CHILUBA',9],
  ],
  girls_14u: [
    [1,'JOYCE NALWIZYA',492],
    [2,'YULA ULENDO',386],
    [3,'YOLANDA PANTOJA',210],
    [4,'SHANEY MATETA',136],
    [5,'MARY KATONGO',117],
    [5,'FAVOUR CHITETA',117],
    [7,'SHALOM SOKO',78],
    [8,'CHIKONDI NKHOMA',72],
    [9,'VAN DER MERWE SOPHIE',69],
    [10,'DEBORAH KUNDA',59],
    [11,'VIOLET ZULU',36],
    [11,'CHITOSHI SHAMIRA',36],
    [13,'NAOMI HAMIYANDA',27],
    [14,'STEFANENU ALEXANDRA',18],
    [14,'GASPAROVA EMILIE',18],
    [14,'KITAIN NICKIE',18],
    [14,'LUNGU CHIKONDI',18],
    [14,'DAVINA KAPEMBWA',18],
    [19,'CHERRY BANDA',9],
    [19,'KAUNDA CHABALA',9],
    [19,'TANDIWE MAKULA MULENGA',9],
    [19,'THANDIWE MAKULALA',9],
    [19,'BANDA EVELY',9],
    [19,'FABBRI MILA',9],
    [19,'ABIGAIL MAZIMBA',9],
  ],
  girls_16u: [
    [1,'MUKANGWA SIAME',480],
    [2,'JANET MWAPE',310],
    [3,'KAYLA MUIMO',308],
    [4,'HECRA PHIRI',72],
    [5,'FELISTUS NKOLE',54],
    [6,'JANE LYAMBAYI',41],
    [7,'SHANET MWEWA',36],
    [7,'LISA CHISONGO',36],
    [9,'DORIS MUZENZE',18],
    [9,'JULIANA MASCRENHAS',18],
    [9,'JANA-ALET HAMMAN',18],
    [9,'KABISEKELA KAPEMBWA',18],
    [13,'ELIEL KWEL',9],
    [13,'ESTHER MULENGA',9],
    [13,'MICHELLE MWANZA',9],
    [16,'PRECIOIUS MUYEMBE',5],
    [17,'TONNY NYIRENDA',0],
    [17,'CHIKONDI PHIRI',0],
    [17,'BLESSINGS NJAVWA',0],
    [17,'FAITH KAMWANGA',0],
    [17,'MWILA VIOLET',0],
    [17,'SIRI NORMAN',0],
    [17,'NTIBA LUNGU',0],
  ],
  girls_18u: [
    [1,'ISABEL CHISONGO',740],
    [2,'CHRISTABEL CHISONGO',436],
    [3,'MITRESS NALWIZYA',280],
    [4,'LOVENESS MAMBWE',162],
    [5,'MWENYA MUKUKA',99],
    [6,'DIANA KITAIN',90],
    [7,'PATRICIA CHIBESA',36],
    [7,'REDA NOOR',36],
    [7,'MUTABA KAPEMBWA',36],
    [10,'ANNIE BURROWS',18],
    [10,'CHANDA MUSONDA',18],
    [10,'ANASTASIA MALIWA MUNDIA',18],
    [10,'ESNART CHISAMU',18],
    [10,'MUSONDA AGATHA',18],
    [10,'TEJESVI BALAMURALI',18],
    [16,'NATASHA WATYAKENI',9],
    [16,'BILLY PAULA',9],
    [16,'HUYNEN LILI-MALYA',9],
    [19,'SHIKHA JASWAL',0],
    [19,'EUNICE CHISAMU',0],
    [19,'BLESSINGS NGULUBE',0],
    [19,'FAITH NAMBAYA',0],
    [19,'NOOR REDA',0],
    [19,'WESSIAN JONES',0],
    [19,'MARGARET KATINABYELA',0],
    [19,'BLESSINGS NJAVWA',0],
  ],
  men_doubles: [
    [1,'KAZEMBE EDGAR',579,'Correctional'],
    [2,'CHILESHE ROBERT',454,'Green Buffaloes'],
    [3,'PHIRI DIXON',297,'Correctional'],
    [4,'MWALE JORDAN',276,'ZNS'],
    [5,'SIMBEYE PETER',246],
    [6,'HAMAYANGWE NAKALANGA',198],
    [7,'CHANSA CHILESHE',164,'Mufulira'],
    [8,'SOKO SYDNEY',126],
    [9,'NKHATA MAXWELL',117],
    [10,'MABO KOMBE SNR',113],
    [11,'MWALE OWEN',108,'ZNS'],
    [12,'NGANDU MOSES',99],
    [13,'MALUNGA MWAMBA',95],
    [13,'KUNDA ABEDNEGO',95],
    [15,'SIMBAYA EDWIN',72],
    [16,'HANGWEWE GIFT',63],
    [17,'NDEFWAI LYTON',60],
    [18,'MABO KOMBE JNR',55],
    [18,'MWALE BLESSING',55],
    [20,'SIMBAYA RICHARD',46],
    [20,'BANDA GRANT',46],
    [22,'MUMBI JUSTINE',41],
    [22,'NTUMBA SYLVESTER',41],
    [22,'BANDA MUMANGO',41],
    [22,'BANDA KONDWANI',41],
    [26,'LUWIKA NATHAN',37],
    [26,'CHISHALA MACMILLAN',37],
    [28,'SIMUKONDA JONATHAN',36],
    [28,'MWALE BENJAMIN',36],
    [30,'MUTAYACHALO KANJA',32],
    [30,'MUKUPA ANDREW',32],
    [32,'MWANZA FRED',28],
    [33,'MANSOUR HITHAN',24],
    [33,'MAMFUNDA CHARLES',24],
    [35,'ZULU CHILITO',23],
    [35,'MULENGA REUBEN',23],
    [35,'MVULA ALEX',23],
    [35,'NKHOMA VICTOR',23],
    [35,'HANKINS JERMAINE',23],
    [40,'MWEENE KALEBI',22],
    [41,'CHIWENA MUWELE',19],
    [41,'EZRA MULENGA',19],
    [41,'CHIMFWEMBE LESA',19],
    [44,'SAMPA REMMY',18],
    [44,'CHICHIMA ISAAC',18],
    [44,'NSAKANYA JOSEPHAT',18],
    [44,'MWANZA CHANDA',18],
    [44,'MATETA SYDNEY',18],
    [49,'TEMBO CHAZANGA',14],
    [49,'GONDWE UNGWELU',14],
    [49,'HAMAYANGWE NABUSANGA',14],
    [49,'BWALE JOSHUA',14],
    [49,'GUPTA OM',14],
    [54,'MANSOUR AHMED',13],
    [55,'KAONGA KENAN',10],
    [55,'SANDO HECTOR',10],
    [55,'NAWA ALBERT',10],
    [55,'SAILI GREG',10],
    [55,'PHIRI CHIMBA',10],
    [55,'KALEBI LUYANDO',10],
    [55,'ENERST SHAMANO',10],
    [62,'MAVUKA JONATHAN',9],
    [62,'MUTALE MULENGA',9],
    [62,'NGALASA ANDREW',9],
    [62,'NSAMA CHILESHE',9],
    [62,'PHIRI CHOYESO',9],
    [62,'MONTA MOSES',9],
    [62,'CHIRWA MARK',9],
    [62,'HAAMIYANDA EUGINE',9],
    [62,'ZULU TOLANI',9],
    [62,'MPEMPULWA SAMUEL',9],
    [62,'MBAZIMA JOEL',9],
    [73,'CHILUBA CHANDA',5],
    [73,'MUSONDA MAPALO',5],
    [73,'FR. MIKE KOLALA',5],
    [73,'PHAKATI REVAI',5],
    [73,'BURROWS JACK',5],
    [73,'SEBASTIAN MORONELL',5],
    [73,'CUMMINGS SCOT',5],
    [73,'KAMANGA POINT',5],
    [73,'SEAMAN MATTHEW',5],
    [73,'ZULU OSWARD',5],
    [73,'MILETIC PAVLE',5],
    [73,'NGWIRA CHRISTOPHER',5],
    [73,'KANGAZA GIFT',5],
    [73,'MUKANDILA C. ROCKY',5],
    [73,'MUSANA FUNGAI',5],
    [73,'MUSONDA AQA',5],
    [73,'MUTALE JUSTINE',5],
    [73,'PHIRI BERNARD',5],
    [73,'CHANDA JUSTINE',5],
    [73,'CHIRWA KONDWA GONDWE',5],
    [73,'SIAME ZANGA',5],
    [73,'MULENGA MALAMBO',5],
    [73,'MUMA ERIC',5],
    [73,'JERE PATULANI',5],
  ],
  women_doubles: [
    [1,'CHRISTABEL CHISONGO',641,'Kantanshi'],
    [2,'ISABEL CHISONGO',636,'Kantanshi'],
    [3,'MARGARET CHEWE',352,'Green Buffaloes'],
    [4,'SORAYA MUMENA',313,'Green Buffaloes'],
    [5,'MUKANGWA SIAME',237],
    [6,'MITRESS NALWIZYA',228],
    [7,'BEATRICE PHIRI',225],
    [7,'MUTALE MAGGIE',225],
    [9,'NALUNGWE NATASHA',188],
    [10,'ANGELA MWANSA',156],
    [11,'KANYAMA HOPE',90],
    [12,'ALICE MULENGA',72],
    [13,'BLESSINGS NGULUBE',63],
    [13,'MWILA IREEN',63],
    [15,'FEBBY CHILEMBO',54],
    [16,'KABANSHI MAGRET',45],
    [16,'KITAIN DIANA',45],
    [16,'VIOLET MULENGA',45],
    [19,'CHEWE EMMY',36],
    [19,'BALAMURALI TEJESVI',36],
    [19,'MWANSA MAMBWE',36],
    [19,'MWENYA MUKUKA',36],
    [19,'MWAPE JANET',36],
    [24,'RUTH NYIRENDA',29],
    [25,'SAZAMBILE PATRICIA',27],
    [26,'MWELWA FAITH',18],
    [26,'CHOONGO LUKUNDO',18],
    [26,'LISA CHISONGO',18],
    [26,'JESSY MUSUNGA',18],
    [26,'PRISCILA KAPUNGWE',18],
    [26,'MEDIA CHISWASWA',18],
    [26,'JOYCE NALWIZYA',18],
    [26,'GONDWE DIANA',18],
    [34,'PATRICIA CHIBESA',9],
    [34,'MULIMA PENELOPE',9],
    [34,'CHIKUKU Y.',9],
    [34,'YOLANDA PANTOJA',9],
    [34,'MUIMO KAYLA',9],
  ],
};

async function findPlayer(name) {
  // Try to find a matching user by name (case-insensitive)
  const tokens = name.trim().split(/\s+/);
  if (tokens.length < 2) return null;
  // Try both "FIRST LAST" and "LAST FIRST" orderings
  const [a, b] = [tokens[0], tokens.slice(1).join(' ')];
  const user = await User.findOne({
    $or: [
      { firstName: new RegExp(`^${a}$`, 'i'), lastName: new RegExp(`^${b}$`, 'i') },
      { firstName: new RegExp(`^${b}$`, 'i'), lastName: new RegExp(`^${a}$`, 'i') },
    ]
  }).select('_id zpin').lean();
  return user || null;
}

async function seed() {
  await mongoose.connect(process.env.MONGO_URI || process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  let created = 0, skipped = 0;

  for (const [category, players] of Object.entries(DATA)) {
    console.log(`\nSeeding ${category} (${players.length} players)...`);

    for (const entry of players) {
      const [rank, rawName, points, club] = entry;
      const name = rawName.trim();

      const exists = await Ranking.findOne({ playerName: name, category, rankingPeriod: PERIOD });
      if (exists) {
        skipped++;
        continue;
      }

      const user = await findPlayer(name);

      const doc = new Ranking({
        playerName: name,
        category,
        rank,
        totalPoints: points,
        rankingPeriod: PERIOD,
        isActive: true,
        club: club || '',
        ...(user ? { playerId: user._id, playerZpin: user.zpin } : {}),
        tournamentResults: points > 0 ? [{
          tournamentName: SEED_TOURNAMENT,
          tournamentDate: SEED_DATE,
          points,
          position: '-',
          year: 2026,
        }] : [],
      });

      await doc.save();
      created++;
    }

    console.log(`  Done ${category}`);
  }

  console.log(`\nSeed complete: ${created} created, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch(err => { console.error(err); process.exit(1); });
